name: myenv
channels:
  - defaults
dependencies:
  - ca-certificates=2024.11.26
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.9.21
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - flatbuffers==24.12.23
      - fonttools==4.55.3
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.68.1
      - h5py==3.12.1
      - idna==3.10
      - imageio==2.36.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - imutils==0.5.4
      - keras==3.7.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - namex==0.0.8
      - numpy==2.0.2
      - opencv-python==4.10.0.84
      - opt-einsum==3.4.0
      - optree==0.13.1
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - protobuf==5.29.2
      - pygments==2.18.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - requests==2.32.3
      - rich==13.9.4
      - scipy==1.13.1
      - six==1.17.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - wrapt==1.17.0
      - zipp==3.21.0